variables:
  commitMessage: $(Build.SourceVersionMessage)
  TF_VAR_location: $(location)
  TF_VAR_resource_group_name: $(resourceGroupName)
  TF_VAR_aks_cluster_name: '$(aksClusterName)-$(Build.BuildId)'

trigger:
- main


pool:
  name: 'azUbuntuAgentPool'

jobs:
  - job: ConditionalTrigger
    condition: ne(variables['commitMessage'], '[Skip]')
    steps:
    # Step 1: Install Terraform
    - script: |
        sudo apt-get update && sudo apt-get install -y unzip
        curl -O https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
        unzip terraform_1.5.0_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform version
      displayName: Install Terraform & Unzip

    # Step 2: Initialize Terraform
    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Azure ARM'
        backendAzureRmResourceGroupName: '$(TF_VAR_resource_group_name)'
        backendAzureRmStorageAccountName: 'tfstateaccount1296'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'tf/terraform.tfstate'

    # Step 2: Validate Terraform
    - task: TerraformTaskV4@4
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'

    # Step 3: Plan Terraform
    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out=tfplan'
        environmentServiceNameAzureRM: 'Azure ARM'

    # Temporary: Check files in current directory
    - script: ls -la
      displayName: Show Current Files
      
    # Step 4: Apply Terraform
    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'Azure ARM'
        environmentVariables: |
          TF_VAR_location=$(location)
          TF_VAR_resource_group_name=$(resourceGroupName)
          TF_VAR_aks_cluster_name=$(aksClusterName)

    # Step 5: Output kubeconfig (optional)
    - script: |
        echo "Kubeconfig:"
        terraform output kube_config
      displayName: 'Output Kubeconfig'